workspace: "/VulBench/workspace" # Path to the workspace

Log:
  level: "info" # Log level (debug, info, warning, error, critical), default is ""
  format: "" # Log format, default is "%(asctime)s\t%(name)s\t%(levelname)s\t[%(filename)s:%(lineno)d]\t%(message)s"

Patch:
  allow_empty_patch: true # Allow empty patches or not. If set to false, the patch will be skipped if it is empty.
  tolerant_valid_patch: true # Whether to consider patches that match tolerant fuzzy patch hunks as valid.

LLM:
  base_url: "" # Base URL for LLM API
  model: "" # Model name
  api_key: "" # Your LLM API key
  stream: false # Set to true if you want to stream the response
  temperature: 0.6 # Temperature for response generation
  top_p: 0.9 # Top-p for response generation
  max_tokens: # Maximum number of tokens in the response
  timeout:  # Timeout for API requests in seconds, and empty value means no timeout. Strongly recommended to set a higher value if using a thinking model without streaming response.
  thinking: false # Set to true if you want the model to think before responding
  thinking_budget: 10240 # Maximum number of tokens for thinking

Browser: # Only for PoC checking
  use_proxy: false # Set to true if you want to use a proxy
  proxy_host: "http://127.0.0.1:7897" # Proxy host
  headless: true # Run in headless mode
  specify: false # Set to true if you want to specify the browser and driver
  driver_path: "" # Path to the specified ChromeDriver executable
  chrome_path: "" # Path to the specified Chrome executable
  remote: false # Set to true if you want to use a remote WebDriver
  remote_url: "http://127.0.0.1:4444/wd/hub" # URL of the remote WebDriver
  chrome_options:
    - "--no-sandbox" # Disable sandboxing
    - "--disable-dev-shm-usage" # Disable /dev/shm usage
    - "--disable-gpu" # Disable GPU acceleration
    - "--disable-setuid-sandbox" # Disable sandboxing
    - "--allow-running-insecure-content" # Allow insecure content
    - "--ignore-ssl-errors=yes" # Ignore SSL errors
    - "--ignore-certificate-errors" # Ignore certificate errors
    - "--disable-notifications" # Disable notifications
  unhandledPromptBehavior: "accept" # Accept unhandled prompts, default is "dismiss"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 VulBench/0.1"